# Generated by Django 3.2.4 on 2021-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
