# Generated by Django 3.2.4 on 2021-06-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_newspictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='NewsPictures',
            new_name='NewsPicture',
        ),
    ]
