# Generated by Django 3.2.4 on 2021-06-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210626_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.new'),
        ),
    ]
